name: my_card_flutter
description: "My Card Flutter App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile.jpg
  
  fonts:
  - family: Pacifico
    fonts:
      - asset: assets/fonts/Pacifico-Regular.ttf

  - family: Source Code Pro
    fonts:
      - asset: assets/fonts/SourceCodePro-Regular.ttf

